### ISSUE TITLE
Übersetzung: Changelog?

### ISSUE THREAD

**Issue by Baumgartl** [DiscoverMeteor/DiscoverMeteor_De#34]

**Comment by tiptronic** [comment]
Übersetzung vom Changelog macht im Grunde vor allem dann Sinn, wenn die deutsche Übersetzung auf dem aktuellen Stand ist, ansonsten halte ich das für eher verwirrend.

a.

**Comment by tiptronic** [comment]
Hello!

 

New message, please read <http://shoroqpress.com/are.php?ne7nn>

 

Andy Fuchs

**Comment by Crenshinibon** [comment]
???

Ich befürchte Dein Account wurde gehackt.

Gruß
Dirk

**Comment by tiptronic** [comment]
Nö... die kommen nicht von mir...
 
andy

**Comment by tiptronic** [comment]
Hey!

 

New message, please read <http://magazinemuzic.com/floor.php?ql4fz>

 

Andy Fuchs

**Comment by nooitaf** [comment]
Och nö, wieder spam von andy's account :( 
Ich hab die Einträge mal gelöscht, ne?
@Crenshinibon kannst du was einleiten? Die letzten 14 Tage ist die Aktivität vom Andy nur Spam irgendwie.

**Comment by nooitaf** [comment]
Hey @SachaG maybe you can have a look at @tiptronic 's activity log of the last 14 days. There is reason to believe his account got compromised. I already removed the 4 spam links here you see in his log. These might also be github account fishing attacks, who knows. 
https://github.com/tiptronic?tab=activity

**Comment by Crenshinibon** [comment]
@nooitaf keine Ahnung, kann ich? Hab leider gerade kaum Zeit mich um das Projekt hier zu kümmern. Hab ich besondere Rechte, hier? Seit wann?

**Comment by nooitaf** [comment]
@Crenshinibon sorry hatte mich verguckt. Dachte weil bei dir "Owner" steht, aber das steht bei mir ja auch xD

**Comment by SachaG** [comment]
OK, I removed @tiptronic from the team for now.

**Comment by tiptronic** [comment]
Why?

**Comment by tiptronic** [comment]
Sorry for the Spam - nothing was compromised - it's a spoofing wave. (if you're interested: read this: http://wardinewrock.blogspot.de/2015/10/domains-spoofed-by.html). He's just sending emails to random email-addresses.

**Comment by SachaG** [comment]
@tiptronic how is your account posting spam links on GitHub without being compromised?

**Comment by tiptronic** [comment]
Read the link I added there

**Comment by SachaG** [comment]
So you mean someone is spoofing your email to post messages to GitHub, and GitHub is getting fooled? Well either way I can't re-add you to the team until you change your GitHub email to one that doesn't have that problem.

**Comment by tiptronic** [comment]
Yes - the mails are definitely not sent through my provider. (They verified that).
But I changed email-adresses already...

a.

**Comment by SachaG** [comment]
OK, I re-added you.
